package cn.com.jinrizhushi;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import cn.com.jinrizhushi.User;
import cn.com.jinrizhushi.Users;
import cn.com.jinrizhushi.CounselorExtInfo;
import cn.com.jinrizhushi.Customer;
import cn.com.jinrizhushi.Order;
import cn.com.jinrizhushi.Students;
import cn.com.jinrizhushi.Teachers;
import cn.com.jinrizhushi.StuAndtea;

import cn.com.jinrizhushi.UserDao;
import cn.com.jinrizhushi.UsersDao;
import cn.com.jinrizhushi.CounselorExtInfoDao;
import cn.com.jinrizhushi.CustomerDao;
import cn.com.jinrizhushi.OrderDao;
import cn.com.jinrizhushi.StudentsDao;
import cn.com.jinrizhushi.TeachersDao;
import cn.com.jinrizhushi.StuAndteaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig usersDaoConfig;
    private final DaoConfig counselorExtInfoDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig studentsDaoConfig;
    private final DaoConfig teachersDaoConfig;
    private final DaoConfig stuAndteaDaoConfig;

    private final UserDao userDao;
    private final UsersDao usersDao;
    private final CounselorExtInfoDao counselorExtInfoDao;
    private final CustomerDao customerDao;
    private final OrderDao orderDao;
    private final StudentsDao studentsDao;
    private final TeachersDao teachersDao;
    private final StuAndteaDao stuAndteaDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        usersDaoConfig = daoConfigMap.get(UsersDao.class).clone();
        usersDaoConfig.initIdentityScope(type);

        counselorExtInfoDaoConfig = daoConfigMap.get(CounselorExtInfoDao.class).clone();
        counselorExtInfoDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        studentsDaoConfig = daoConfigMap.get(StudentsDao.class).clone();
        studentsDaoConfig.initIdentityScope(type);

        teachersDaoConfig = daoConfigMap.get(TeachersDao.class).clone();
        teachersDaoConfig.initIdentityScope(type);

        stuAndteaDaoConfig = daoConfigMap.get(StuAndteaDao.class).clone();
        stuAndteaDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        usersDao = new UsersDao(usersDaoConfig, this);
        counselorExtInfoDao = new CounselorExtInfoDao(counselorExtInfoDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        studentsDao = new StudentsDao(studentsDaoConfig, this);
        teachersDao = new TeachersDao(teachersDaoConfig, this);
        stuAndteaDao = new StuAndteaDao(stuAndteaDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Users.class, usersDao);
        registerDao(CounselorExtInfo.class, counselorExtInfoDao);
        registerDao(Customer.class, customerDao);
        registerDao(Order.class, orderDao);
        registerDao(Students.class, studentsDao);
        registerDao(Teachers.class, teachersDao);
        registerDao(StuAndtea.class, stuAndteaDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        usersDaoConfig.getIdentityScope().clear();
        counselorExtInfoDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        studentsDaoConfig.getIdentityScope().clear();
        teachersDaoConfig.getIdentityScope().clear();
        stuAndteaDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public UsersDao getUsersDao() {
        return usersDao;
    }

    public CounselorExtInfoDao getCounselorExtInfoDao() {
        return counselorExtInfoDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public StudentsDao getStudentsDao() {
        return studentsDao;
    }

    public TeachersDao getTeachersDao() {
        return teachersDao;
    }

    public StuAndteaDao getStuAndteaDao() {
        return stuAndteaDao;
    }

}
