package cn.com.jinrizhushi;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User implements java.io.Serializable {

    private Long id;
    private Integer attitudes_count;
    private String avatar_default;
    private String avatar_hd;
    private String avatar_large;
    private Integer comments_count;
    private Integer authentication;
    private String certificationGroup;
    private String create_time;
    private String description_content;
    private Integer favourites_count;
    private Integer followers_count;
    private Integer friends_count;
    private Integer gender;
    private Integer identifier;
    private String mobile;
    private String nick_name;
    private String real_name;
    private String password;
    private Integer point_count;
    private Integer user_type;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer attitudes_count, String avatar_default, String avatar_hd, String avatar_large, Integer comments_count, Integer authentication, String certificationGroup, String create_time, String description_content, Integer favourites_count, Integer followers_count, Integer friends_count, Integer gender, Integer identifier, String mobile, String nick_name, String real_name, String password, Integer point_count, Integer user_type) {
        this.id = id;
        this.attitudes_count = attitudes_count;
        this.avatar_default = avatar_default;
        this.avatar_hd = avatar_hd;
        this.avatar_large = avatar_large;
        this.comments_count = comments_count;
        this.authentication = authentication;
        this.certificationGroup = certificationGroup;
        this.create_time = create_time;
        this.description_content = description_content;
        this.favourites_count = favourites_count;
        this.followers_count = followers_count;
        this.friends_count = friends_count;
        this.gender = gender;
        this.identifier = identifier;
        this.mobile = mobile;
        this.nick_name = nick_name;
        this.real_name = real_name;
        this.password = password;
        this.point_count = point_count;
        this.user_type = user_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getAttitudes_count() {
        return attitudes_count;
    }

    public void setAttitudes_count(Integer attitudes_count) {
        this.attitudes_count = attitudes_count;
    }

    public String getAvatar_default() {
        return avatar_default;
    }

    public void setAvatar_default(String avatar_default) {
        this.avatar_default = avatar_default;
    }

    public String getAvatar_hd() {
        return avatar_hd;
    }

    public void setAvatar_hd(String avatar_hd) {
        this.avatar_hd = avatar_hd;
    }

    public String getAvatar_large() {
        return avatar_large;
    }

    public void setAvatar_large(String avatar_large) {
        this.avatar_large = avatar_large;
    }

    public Integer getComments_count() {
        return comments_count;
    }

    public void setComments_count(Integer comments_count) {
        this.comments_count = comments_count;
    }

    public Integer getAuthentication() {
        return authentication;
    }

    public void setAuthentication(Integer authentication) {
        this.authentication = authentication;
    }

    public String getCertificationGroup() {
        return certificationGroup;
    }

    public void setCertificationGroup(String certificationGroup) {
        this.certificationGroup = certificationGroup;
    }

    public String getCreate_time() {
        return create_time;
    }

    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

    public String getDescription_content() {
        return description_content;
    }

    public void setDescription_content(String description_content) {
        this.description_content = description_content;
    }

    public Integer getFavourites_count() {
        return favourites_count;
    }

    public void setFavourites_count(Integer favourites_count) {
        this.favourites_count = favourites_count;
    }

    public Integer getFollowers_count() {
        return followers_count;
    }

    public void setFollowers_count(Integer followers_count) {
        this.followers_count = followers_count;
    }

    public Integer getFriends_count() {
        return friends_count;
    }

    public void setFriends_count(Integer friends_count) {
        this.friends_count = friends_count;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Integer getIdentifier() {
        return identifier;
    }

    public void setIdentifier(Integer identifier) {
        this.identifier = identifier;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getNick_name() {
        return nick_name;
    }

    public void setNick_name(String nick_name) {
        this.nick_name = nick_name;
    }

    public String getReal_name() {
        return real_name;
    }

    public void setReal_name(String real_name) {
        this.real_name = real_name;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getPoint_count() {
        return point_count;
    }

    public void setPoint_count(Integer point_count) {
        this.point_count = point_count;
    }

    public Integer getUser_type() {
        return user_type;
    }

    public void setUser_type(Integer user_type) {
        this.user_type = user_type;
    }

}
